### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/chembox#29]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

### 1. Team work contract

Good job!

### 2. Create project structure for the python project (40 points)
- [x] The README.md hasn't a bulleted list of the functions and datasets that are included in the package - mechanics -2

*Comments:* I am guessing that the project would use a dataset containing the molecular weights, atomic radius and other properties for each elements. Would be good to include a script to download this data or include the dataset within the repo and mention it in the README.

### 3. Function specifications (20 points)

Good job!

### 4. Manage issues (10 points)
Good job!

### 5. Specific expectations for this milestone are: (10 points)

Good job!

### 6. Submission instructions (10 points)
Good job!

**Comment by Suraporn** [comment]
Close.
